// calc2_parser.minimal.bison.y

// calc2 minimal parser without semantic actions to test grammar with real input
// bison --color=always -Wall -Wdangling-alias -Werror -Wcounterexamples --report counterexamples,lookaheads --report-file calc2_grammar_report.minimal.txt calc2_parser.minimal.bison.y

// c++ parser classes skeleton file
%skeleton "lalr1.cc"

%require "3.8.2"

// c++ parser
%language "c++"

// generate parser description report .output file
%verbose

// enable debug trace
%define parse.trace

// adds location parameter to symbol constructors
%locations

// generate header for location class
%define api.location.file "calc2_locations.minimal.bison.h"

// handle errors in error() method
%define parse.error detailed

// better lookup performance at cost of disallowing literal characters in grammar
%define api.token.raw

// use C++ types for tokens
%define api.value.type variant

// each token type has its own factory function, change yylex return type to Calc2Parser::symbol_type
%define api.token.constructor

%code requires {
// %code requires codeblock goes at top of .h outside of namespace and parser class
// standard c++ #includes and defines

#include <stdint.h>

#include <string>
#include <functional>

#include "calc2_locations.minimal.bison.h"

#ifdef _MSC_VER
// begin disable vc++ warning C4065 in .h file, switch statement contains default but no case labels in code generated for basic_symbol::clear()
#pragma warning(push)
#pragma warning(disable: 4065)
#endif

namespace calc2min {
using namespace std;

// info for lexer to use in yylex
struct LexParam {
// position in input stream for lexer to update
  location loc{};
};

}

}

// custom namespace generated by bison
%define api.namespace {calc2min}

// custom classname generated by bison
%define api.parser.class {Calc2MinParser}

// parser constructor parameter 1
// this is the yylex bison will call, it can have any signature we want since it's a lambda passed in by the client that wraps and hides the actual yylex call
%parse-param {function<Calc2MinParser::symbol_type(LexParam&)> yylex}

// parser constructor parameter 2
// only because each lex-param also must be parse-param
%parse-param {LexParam& lexParam}

// yylex parameter 1
// pass location and lexical feedback info to lexer
%lex-param {LexParam& lexParam}

%define parse.assert

%code provides {
// %code provides codeblock
// goes in .h after namespace and parser class
// everything here needs Calc2Parser defined earlier

#ifdef _MSC_VER
// end disable vc++ warning C4065 in .h file, switch statement contains default but no case labels in code generated for basic_symbol::clear()
#pragma warning(pop)
#endif

}

%code top {
// % code top
// appears as topmost code block in generated .cpp file just below gnu license
// your license for .cpp file

}

%{
// %{ unnamed codeblock
// goes at top of .cpp file after %code top, before namespace and parser class

%}

%code {
// %code
// appears in generated .cpp file after #include of generated .h file and before parser namespace and class

#include <string>
#include <print>

#ifdef _MSC_VER
// begin disable vc++ warning C4065 in .cpp file, switch statement contains default but no other case labels when there are no semantic actions
#pragma warning(push)
#pragma warning(disable: 4065)
#endif

using namespace std;

namespace {
  const auto defaultInputName = "input"s;
}

void calc2min::Calc2MinParser::error(const location& loc, const string& msg) {
  const auto [file, line, col] = loc.begin;
  println("error at {}:{}.{}: {}", *file, line, col, msg);
}

}

%initial-action {
// %initial-action codeblock
// goes inside parse() function in .cpp, it's a separate brace-scoped block, anything declared here is local to this block and cannot be used anywhere else in parse()

// suppress unused variable warning till fix in release after version 3.8.2, https://github.com/akimd/bison/commit/a166d5450e3f47587b98f6005f9f5627dbe21a5b
// yynerrs_ is local to generated parse function
  (void)yynerrs_;

  auto& loc = lexParam.loc;

  if(loc.begin.filename == nullptr) {
    loc.initialize(&defaultInputName);
  }
}


%token              DIV            "/"
%token              EQUAL          "="
%token              LEFT_PAREN     "("
%token              MINUS          "-"
%token              PLUS           "+"
%token              RIGHT_PAREN    ")"
%token              SEMICOLON      ";"
%token              TIMES          "*"

%token <string>     IDENT          "ident"
%token <int64_t>    INT            "int"

%start expr

%%

expr: assign_exprs | assign_exprs ";"

assign_exprs: assign_expr | assign_exprs ";" assign_expr

assign_expr: IDENT "=" assign_expr | add_expr

add_expr: term | add_expr "+" term | add_expr "-" term

term: unary | term "*" unary | term "/" unary

unary: atom | "+" unary | "-" unary

atom: INT | IDENT | "(" assign_expr ")"


%%
// %code epilog block
// goes at bottom of generated .cpp file after namespace and parser implementation

#ifdef _MSC_VER
// end disable vc++ warning C4065 in .cpp file, switch statement contains default but no case labels in code generated for basic_symbol::clear()
#pragma warning(pop)
#endif

