// calc1_parser.bison.y

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// bison --color=always -Wall -Wdangling-alias -Werror -Wcounterexamples --report counterexamples,lookaheads --report-file bisonreport.txt calc1_parser.bison.y

// c++ parser classes skeleton file
%skeleton "lalr1.cc"

%require "3.8.2"

// c++ parser
%language "c++"

// generate parser description report .output file
%verbose

// enable debug trace
%define parse.trace

// adds location parameter to symbol constructors
%locations

// generate header for location class
%define api.location.file "calc1_locations.bison.h"

// handle errors in error() method
%define parse.error detailed

// better lookup performance at cost of disallowing literal characters in grammar
%define api.token.raw

// use C++ types for tokens
%define api.value.type variant

// each token type has its own factory function, change yylex return type to Calc1Parser::symbol_type
%define api.token.constructor

%code requires {
// %code requires codeblock goes at top of .h outside of namespace and parser class
// standard c++ #includes and defines

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <stdint.h>

#include <string>
#include <functional>
#include <unordered_map>
#include <print>

#include "calc1_locations.bison.h"

#ifdef _MSC_VER
// begin disable vc++ warning C4065 in .h file, switch statement contains default but no case labels in code generated for basic_symbol::clear()
#pragma warning(push)
#pragma warning(disable: 4065)
#endif

namespace calc1 {
using namespace std;

struct BisonParam {
  int64_t expr = -1;
  unordered_map<string, int64_t> symtab;
};

// info for lexer to use in yylex
struct LexParam {
// position in input stream for lexer to update
  location loc{};
};

}

}

// custom namespace generated by bison
%define api.namespace {calc1}

// custom classname generated by bison
%define api.parser.class {Calc1Parser}

// parser constructor parameter 1
// this is the yylex bison will call, it can have any signature we want since it's a lambda passed in by the client that wraps and hides the actual yylex call
%parse-param {function<Calc1Parser::symbol_type(LexParam&)> yylex}

// parser constructor parameter 2
%parse-param {BisonParam& bisonParam}

// parser constructor parameter 3
// only because each lex-param also must be parse-param
%parse-param {LexParam& lexParam}

// yylex parameter 1
// pass location and lexical feedback info to lexer
%lex-param {LexParam& lexParam}

%define parse.assert

%code provides {
// %code provides codeblock
// goes in .h after namespace and parser class
// everything here needs Calc1Parser defined earlier

#ifdef _MSC_VER
// end disable vc++ warning C4065 in .h file, switch statement contains default but no case labels in code generated for basic_symbol::clear()
#pragma warning(pop)
#endif

}

%code top {
// % code top
// appears as topmost code block in generated .cpp file just below gnu license
// your license for .cpp file

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

}

%{
// %{ unnamed codeblock
// goes at top of .cpp file after %code top, before namespace and parser class

%}

%code {
// %code
// appears in generated .cpp file after #include of generated .h file and before parser namespace and class

#include <string>
#include <print>

#ifdef _MSC_VER
// begin disable vc++ warning C4065 in .cpp file, switch statement contains default but no other case labels when there are no semantic actions
#pragma warning(push)
#pragma warning(disable: 4065)
#endif

using namespace std;

namespace {
  const auto defaultInputName = "inputstream"s;
}

void calc1::Calc1Parser::error(const location& loc, const string& msg) {
  const auto [file, line, col] = loc.begin;
  println("error at {}:{}.{}: {}", *file, line, col, msg);
}

}

%initial-action {
// %initial-action codeblock
// goes inside parse() function in .cpp, it's a separate brace-scoped block, anything declared here is local to this block and cannot be used anywhere else in parse()

// suppress unused variable warning till fix in release after version 3.8.2, https://github.com/akimd/bison/commit/a166d5450e3f47587b98f6005f9f5627dbe21a5b
// yynerrs_ is local to generated parse function
  (void)yynerrs_;

  auto& loc = lexParam.loc;

  if(loc.begin.filename == nullptr) {
    loc.initialize(&defaultInputName);
  }
}

%token DIV                  "/"
%token EQUAL                "="
%token LEFT_PAREN           "("
%token MINUS                "-"
%token PLUS                 "+"
%token RIGHT_PAREN          ")"
%token SEMICOLON            ";"
%token TIMES                "*"

%token <string>             IDENT        "ident"
%token <int64_t>            INT          "int"

%nterm <int64_t>            add_expr
%nterm <int64_t>            assign_expr
%nterm <int64_t>            assign_exprs
%nterm <int64_t>            atom
%nterm <int64_t>            expr
%nterm <int64_t>            unary
%nterm <int64_t>            term

%start expr

%%

// no code allowed in rules section, just bison comments that are dropped from .cpp

expr:
  assign_exprs {
  $$ = $assign_exprs;
  bisonParam.expr = $$;
}
| assign_exprs ";" {
  $$ = $assign_exprs;
  bisonParam.expr = $$;
}

// right-recursive for right associative assignment
assign_exprs:
  assign_expr {
  $$ = $assign_expr;
}
| assign_exprs ";" assign_expr {
  $$ = $assign_expr;
}

assign_expr:
  IDENT "=" assign_expr[rhs] {
  if(!bisonParam.symtab.contains($IDENT)) {
    bisonParam.symtab[$IDENT] = 0;
  }
  bisonParam.symtab[$IDENT] = $rhs;
  $$ = bisonParam.symtab[$IDENT];
}
| add_expr {
  $$ = $add_expr;
}

add_expr:
  term {
  $$ = $term;
}
| add_expr "+" term {
  $$ = $1 + $term;
}
| add_expr "-" term {
  $$ = $1 - $term;
}

term:
  unary {
  $$ = $unary;
}
| term "*" unary {
  $$ = $1 * $unary;
}
| term "/" unary {
  $$ = $1 / $unary;
}

unary:
  atom {
  $$ = $atom;
}
| "+" unary[rhs] {
  $$ = $rhs;
}
| "-" unary [rhs]{
  $$ = -1 * $rhs;
}

atom:
  INT {
  $$ = $INT;
}
| IDENT {
  if(!bisonParam.symtab.contains($IDENT)) {
    bisonParam.symtab[$IDENT] = 0;
  }
  $$ = bisonParam.symtab[$IDENT];
}
| "(" assign_expr ")" {
  $$ = $assign_expr;
}

%%
// %code epilog block
// goes at bottom of generated .cpp file after namespace and parser implementation

#ifdef _MSC_VER
// end disable vc++ warning C4065 in .cpp file, switch statement contains default but no case labels in code generated for basic_symbol::clear()
#pragma warning(pop)
#endif

